// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Audible.Tag.getTag(System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Audible.Tag.setTag(System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Aac.File.GetTag(TagLib.TagTypes,System.Boolean)~TagLib.Tag")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Ape.File.GetTag(TagLib.TagTypes,System.Boolean)~TagLib.Tag")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Flac.File.GetTag(TagLib.TagTypes,System.Boolean)~TagLib.Tag")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Mpeg.AudioFile.GetTag(TagLib.TagTypes,System.Boolean)~TagLib.Tag")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Mpeg.File.GetTag(TagLib.TagTypes,System.Boolean)~TagLib.Tag")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.MusePack.File.GetTag(TagLib.TagTypes,System.Boolean)~TagLib.Tag")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Png.File.Decompress(System.Byte,TagLib.ByteVector)~TagLib.ByteVector")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.WavPack.File.GetTag(TagLib.TagTypes,System.Boolean)~TagLib.Tag")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Mpeg.AudioHeader.AudioLayer")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Mpeg.AudioHeader.Version")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Riff.BitmapInfoHeader.Description")]
[assembly: SuppressMessage("Style", "IDE0066:Switch-Anweisung in Ausdruck konvertieren", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Riff.WaveFormatEx.Description")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.ByteVector.ToString(TagLib.StringType,System.Int32,System.Int32)~System.String")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.ByteVector.ToStrings(TagLib.StringType,System.Int32,System.Int32)~System.String[]")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.File.Create(TagLib.File.IFileAbstraction,System.String,TagLib.ReadStyle)~TagLib.File")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Genres.StringToByte(System.String)~System.Byte")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Id3v2.TextInformationFrame.ParseRawData")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Ogg.XiphComment.Parse(TagLib.ByteVector)")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.StringCollection.Split(System.String,System.String)~TagLib.StringCollection")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Xmp.XmpTag.#ctor(System.String,TagLib.File)")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Asf.Tag.Genres")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Id3v2.Tag.ReplayGainAlbumGain")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Id3v2.Tag.ReplayGainTrackGain")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Matroska.Tag.Genres")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Ogg.XiphComment.ReplayGainAlbumGain")]
[assembly: SuppressMessage("Style", "IDE0057:Bereichsoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~P:TagLib.Ogg.XiphComment.ReplayGainTrackGain")]
[assembly: SuppressMessage("Usage", "CA2211:Nicht konstante Felder dürfen nicht sichtbar sein", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Jpeg.Table.StandardChrominanceQuantization")]
[assembly: SuppressMessage("Usage", "CA2211:Nicht konstante Felder dürfen nicht sichtbar sein", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Jpeg.Table.StandardLuminanceQuantization")]
[assembly: SuppressMessage("Usage", "CA2211:Nicht konstante Felder dürfen nicht sichtbar sein", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Xmp.XmpTag.NamespacePrefixes")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose-Methoden müssen SuppressFinalize aufrufen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.File.Dispose")]
[assembly: SuppressMessage("Style", "IDE0056:Indexoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Id3v2.TextInformationFrame.ParseRawData")]
[assembly: SuppressMessage("Style", "IDE0056:Indexoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Mpeg4.File.Save")]
[assembly: SuppressMessage("Style", "IDE0056:Indexoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Ogg.Paginator.AddPage(TagLib.Ogg.Page)")]
[assembly: SuppressMessage("Style", "IDE0056:Indexoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Ogg.XiphComment.Parse(TagLib.ByteVector)")]
[assembly: SuppressMessage("Style", "IDE0056:Indexoperator verwenden", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Xmp.XmpTag.#ctor(System.String,TagLib.File)")]
[assembly: SuppressMessage("Style", "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Aac.AudioHeader.#ctor(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Style", "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Audible.File.#ctor(TagLib.File.IFileAbstraction,TagLib.ReadStyle)")]
[assembly: SuppressMessage("Style", "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Audible.Tag.#ctor(TagLib.Audible.File,System.Int64)")]
[assembly: SuppressMessage("Style", "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.IFD.IFDReader.ParseMakernote(System.UInt16,System.UInt16,System.UInt32,System.Int64,System.UInt32)~TagLib.IFD.IFDEntry")]
[assembly: SuppressMessage("Style", "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Image.NoMetadata.File.#ctor(TagLib.File.IFileAbstraction,TagLib.ReadStyle)")]
[assembly: SuppressMessage("Style", "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Jpeg.File.ReadSOFSegment(System.Int32,TagLib.Jpeg.Marker)")]
[assembly: SuppressMessage("Style", "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Matroska.File.Read(TagLib.ReadStyle)")]
[assembly: SuppressMessage("Style", "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Mpeg4.IsoFreeSpaceBox.#ctor(TagLib.Mpeg4.BoxHeader,TagLib.File,TagLib.Mpeg4.IsoHandlerBox)")]
[assembly: SuppressMessage("Style", "IDE0060:Nicht verwendete Parameter entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Png.File.Inflate(TagLib.ByteVector)~TagLib.ByteVector")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.AudioTrack.depth")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.File.title")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.Track.codec_data")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.Track.track_codec_id")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.Track.track_default")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.Track.track_enabled")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.Track.track_name")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.Track.track_number")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.Track.track_uid")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.VideoTrack.disp_height")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.VideoTrack.disp_width")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.VideoTrack.fourcc")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.VideoTrack.framerate")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.VideoTrack.interlaced")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:TagLib.Matroska.VideoTrack.ratio_type")]
[assembly: SuppressMessage("Style", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:TagLib.Id3v2.Frame.FieldData(TagLib.ByteVector,System.Int32,System.Byte)~TagLib.ByteVector")]
