// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.CLIP.CLIPGenericStatus")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.CLIP.CLIPGenericStatusConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.CLIP.CLIPGenericStatusState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.CLIP.CLIPPresence")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.CLIP.CLIPPresenceConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.CLIP.CLIPPresenceState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.CLIP.CLIPSwitch")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.CLIP.CLIPSwitchConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.CLIP.CLIPSwitchState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.DaylightSensor")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.DaylightSensorConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.DaylightSensorState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Xiaomi.GenericXiaomi")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Xiaomi.GenericXiaomiConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Xiaomi.GenericXiaomiState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZGPSwitch")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZGPSwitchConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZGPSwitchState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAAlarm")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAAlarmConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAAlarmState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHACarbonMonoxide")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHACarbonMonoxideConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHACarbonMonoxideState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAConsumption")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAConsumptionConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAConsumptionState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAFire")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAFireConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAFireState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAHumidity")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAHumidityConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAHumidityState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHALightLevel")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHALightLevelConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHALightLevelState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAOpenClose")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAOpenCloseConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAOpenCloseState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAPower")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAPowerConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAPowerState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAPresence")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAPresenceConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAPresenceState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAPressure")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAPressureConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAPressureState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHASwitch")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHASwitchConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHASwitchState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHATemperature")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHATemperatureConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHATemperatureState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAThermostat")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAThermostatConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAThermostatState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAVibration")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAVibrationConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAVibrationState")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAWater")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAWaterConfig")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:InnerCore.Api.DeConz.Models.Sensors.Zigbee.ZHAWaterState")]

